---
ssh_port: 22113
ssh_permit_root_login: "no"
ssh_password_authentication: "yes"
ssh_kbd_interactive_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_max_auth_tries: 3
ssh_max_sessions: 10
ssh_max_startups: "10:30:60"
ssh_x11_forwarding: "no"
ssh_allow_agent_forwarding: "no"
ssh_allow_tcp_forwarding: "no"
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_permit_user_environment: "no"

firewall_ssh_port: "{{ ssh_port }}"

hardening_packages:
  - openssh-server
  - nftables
  - fail2ban
  - unattended-upgrades
  - lynis
